project:
  type: website
  output-dir: docs

website:
  title: "Laundry Research"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - Consumer_motivations.qmd
      - Environmental_impacts.qmd
      - published_articles.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



