project:
  type: website
  output-dir: docs

website:
  title: "Laundry Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - published_articles.qmd
      - Consumer_motivations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



